paypal:
  client:
    id: *************************************
    secret: ***********************************************
  mode: sandbox
server:
  port: 9090
spring:
  application:
    name: payment-gateway-service
  config:
    import: configserver:http://localhost:9296
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: 'off'
